image: maven:latest

variables:
  MYSQL_DATABASE: "test"
  MYSQL_ROOT_PASSWORD: ""
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "dbpass"
  MYSQL_HOST: mysql

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  services:
    - mysql:latest
  script:
    - mvn test
