image: gradle:alpine

variables:
  MYSQL_DATABASE: test
  MYSQL_ROOT_PASSWORD: strongpassword
  DB_URL: jdbc:mysql://mysql:3306/test?allowPublicKeyRetrieval=true&useSSL=false

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
  key: "$CI_BUILD_REF_NAME"

stages:
  - build

build:
  stage: build
  script: ./gradlew build
  services:
    - mysql:latest
  artifacts:
    paths:
      - "paradubschmanager/build/libs/"
      - "craftinglib/build/libs/"