# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push]

permissions:
  contents: read

env:
  DB_URL: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useSSL=false
  MYSQL_ROOT_PASSWORD: strongpassword

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache Gradle packages
        id: cache-gradle
        uses: actions/cache@v3
        env:
          cache-name: cache-gradle-modules
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'test'
          mysql root password: 'strongpassword'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --stacktrace --scan --info
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            craftinglib/build/libs/